github.com:
    users:
        MisterioSST:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: MisterioSST
